import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("malowanie-na-zywo-wesele", "routes/malowanie-na-zywo-wesele.tsx"),
  route("live-painting-wesele", "routes/legacy-redirect.ts", { id: "legacy-wesele" }),
  route("live-painting-eventy", "routes/legacy-redirect.ts", { id: "legacy-eventy" }),
  route("live-painting-warszawa", "routes/legacy-redirect.ts", { id: "legacy-warszawa" }),
  route("live-painting-trojmiasto", "routes/legacy-redirect.ts", { id: "legacy-trojmiasto" }),
  route("malowanie-na-zywo-eventy", "routes/malowanie-na-zywo-eventy.tsx"),
  route("malowanie-na-zywo-warszawa", "routes/malowanie-na-zywo-warszawa.tsx"),
  route("malowanie-na-zywo-trojmiasto", "routes/malowanie-na-zywo-trojmiasto.tsx"),
  route("portrety-na-zamowienie", "routes/portrety-na-zamowienie.tsx"),
  route("realizacje", "routes/realizacje.tsx"),
  route("cennik", "routes/cennik.tsx"),
  route("o-mnie", "routes/o-mnie.tsx"),
  route("terminy", "routes/terminy.tsx"),
  route("kontakt", "routes/kontakt.tsx"),
  route("polityka-prywatnosci", "routes/polityka-prywatnosci.tsx"),
  route("blog", "routes/blog.tsx"),
  route("blog/:slug", "routes/blog-post.tsx"),
  route("test-tla", "routes/test-tla.tsx"),
  route("media/*", "routes/media.ts"),
  route("sitemap.xml", "routes/sitemap.ts"),
] satisfies RouteConfig;
